import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import sasLogo from "../../assets/saslogo.jpg"; // your logo
import "./AddFreshTeaLeaves.css";

const AddFreshTeaLeaves = () => {
  const API_URL = "http://localhost:5000/api/tea-leaves";
  //const EMAIL_API_URL = "http://localhost:5000/api/send-email"; // your backend email route

  const [leaves, setLeaves] = useState([]);
  const [formData, setFormData] = useState({
    id: "",
    supplierName: "",
    email: "",
    weight: 0,
    pricePerKg: 0,
  });

  const fetchLeaves = async () => {
    try {
      const res = await axios.get(API_URL);
      setLeaves(res.data);
    } catch (err) {
      console.error("Error fetching tea leaves:", err);
    }
  };

  useEffect(() => {
    fetchLeaves();
  }, []);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const data = {
      supplierName: formData.supplierName,
      email: formData.email,
      weight: Number(formData.weight),
      pricePerKg: Number(formData.pricePerKg),
    };

    try {
      if (formData.id) {
        await axios.put(`${API_URL}/${formData.id}`, data);
      } else {
        await axios.post(API_URL, data);
      }
      setFormData({ id: "", supplierName: "", email: "", weight: 0, pricePerKg: 0 });
      fetchLeaves();
    } catch (err) {
      console.error(err);
      alert("Failed to submit tea leaves.");
    }
  };

  const handleEdit = (leaf) => {
    setFormData({
      id: leaf._id,
      supplierName: leaf.supplierName,
      email: leaf.email,
      weight: leaf.weight,
      pricePerKg: leaf.pricePerKg,
    });
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure?")) return;
    try {
      await axios.delete(`${API_URL}/${id}`);
      fetchLeaves();
    } catch (err) {
      console.error(err);
    }
  };

  const handleOpenEmail = (leaf) => {
  const email = "recipient@example.com"; // or dynamic
  const subject = encodeURIComponent(`Fresh Tea Leaves Info - ${leaf.supplierName}`);
  const body = encodeURIComponent(
    `Hello,\n\nHere is the tea leaves info:\nSupplier: ${leaf.supplierName}\nWeight: ${leaf.weight} kg\nPrice per Kg: ${leaf.pricePerKg}\nTotal Price: ${leaf.totalPrice}\n\nThanks.`
  );

  window.location.href = `mailto:${email}?subject=${subject}&body=${body}`;
};


  // ✅ Generate PDF for one record
  const generatePDF = (leaf) => {
    const doc = new jsPDF("p", "pt", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();

    // Logo
    const imgWidth = 80;
    const imgHeight = 80;
    doc.addImage(sasLogo, "JPEG", (pageWidth - imgWidth) / 2, 20, imgWidth, imgHeight);

    doc.setFontSize(18);
    doc.setTextColor("#1f3a93");
    doc.text("Fresh Tea Leaves Report", pageWidth / 2, 120, { align: "center" });

    doc.setFontSize(12);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 50, 140, {
      align: "right",
    });

    const rows = [
      ["Supplier Name", leaf.supplierName],
      ["Email", leaf.email || "-"],
      ["Weight (kg)", leaf.weight],
      ["Price Per Kg", leaf.pricePerKg],
      ["Total Price", leaf.totalPrice],
    ];

    autoTable(doc, {
      startY: 160,
      head: [["Field", "Value"]],
      body: rows,
      theme: "grid",
      headStyles: { fillColor: "#2980b9", textColor: "#fff", halign: "center" },
      alternateRowStyles: { fillColor: "#f2f2f2" },
    });

    // Signature area
    const finalY = doc.lastAutoTable.finalY + 40;
    doc.text("Authorized Signature:", 40, finalY);
    doc.line(180, finalY, 400, finalY);

    doc.setFontSize(10);
    doc.setTextColor("#555");
    doc.text("Generated by Tea Factory System", pageWidth / 2, 800, { align: "center" });

    doc.save(`TeaLeaves_${leaf.supplierName}.pdf`);
  };

  // ✅ Send Email
  /*const sendEmail = async (leaf) => {
    try {
      await axios.post(EMAIL_API_URL, {
        to: leaf.email,
        subject: "Fresh Tea Leaves Order",
        message: `Hello ${leaf.supplierName}, your tea leaves order details:\nWeight: ${leaf.weight} kg\nPrice: ${leaf.pricePerKg}/kg\nTotal: ${leaf.totalPrice}`,
      });
      alert("Email sent successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to send email");
    }
  }; */

  return (
    <div className="fresh-leaves-container">
      <div className="fresh-leaves-content">
        <h1>Fresh Tea Leaves Inventory</h1>

        <form className="form" onSubmit={handleSubmit}>
          <input
            name="supplierName"
            placeholder="Supplier Name"
            value={formData.supplierName}
            onChange={handleChange}
            required
          />
          <input
            name="email"
            type="email"
            placeholder="Supplier Email"
            value={formData.email}
            onChange={handleChange}
            required
          />
          <input
            name="weight"
            type="number"
            placeholder="Weight (kg)"
            value={formData.weight}
            onChange={handleChange}
            required
          />
          <input
            name="pricePerKg"
            type="number"
            step="0.01"
            placeholder="Price per Kg"
            value={formData.pricePerKg}
            onChange={handleChange}
            required
          />
          <button type="submit">{formData.id ? "Update" : "Add"}</button>
        </form>

        <div className="table-container">
          <h3>All Tea Leaves</h3>
          <table>
            <thead>
              <tr>
                <th>Supplier</th>
                <th>Email</th>
                <th>Weight (kg)</th>
                <th>Price/Kg</th>
                <th>Total Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {leaves.map((l) => (
                <tr key={l._id}>
                  <td>{l.supplierName}</td>
                  <td>{l.email}</td>
                  <td>{l.weight}</td>
                  <td>{l.pricePerKg}</td>
                  <td>{l.totalPrice}</td>
                  <td>
                    <button className="edit-btn" onClick={() => handleEdit(l)}>
                      Edit
                    </button>
                    <button className="delete-btn" onClick={() => handleDelete(l._id)}>
                      Delete
                    </button>
                    <button className="pdf-btn" onClick={() => generatePDF(l)}>
                      PDF
                    </button>
                    {/* Email button */}
  <button
    className="email-btn"
    onClick={() => handleOpenEmail(l)}
  >
    Email
  </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default AddFreshTeaLeaves;
